name: Build documentation

on: [push]

defaults:
  run:
    working-directory: docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build
        run: sh build.sh
      - name: Upload
        env: 
          FOLGE_URL: https://app.folge.io
          FOLGE_TOKEN: ${{ secrets.FOLGE_TOKEN }}
        run: |
          pip install folge-cli
          folge-cli upload-docs --organization=lab-digital --docs-key=${{ secrets.FOLGE_DOCS_KEY }} build