name: Build documentation

on:
  push:
    paths:
    - 'docs/**/*'

defaults:
  run:
    working-directory: docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          python -m pip install -r requirements.txt
          sh build.sh
      - name: Upload
        env: 
          FOLGE_URL: https://app.folge.io
        run: |
          pip install folge-cli
          folge-cli upload-docs --organization=lab-digital --docs-key=${{ secrets.FOLGE_DOCS_KEY }} build